import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title> JSB Residences</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/static/logo.ico" />
      </Head>
       
      <main>
       <div id="carouselExampleIndicators" className="carousel slide" data-bs-ride="true">
        <div className="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" className="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div className="carousel-inner">
            <picture className="carousel-item active">
             <img src="/static/slider_1.png" className="d-block w-100" alt="..."/>
            </picture>
            <picture className="carousel-item">
             <img src="/static/slider_2.png" className="d-block w-100" alt="..."/>
            </picture>
            <picture className="carousel-item">
             <img src="/static/slider_3.png" className="d-block w-100" alt="..."/>
            </picture>
        </div>
        <button className="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span className="carousel-control-prev-icon" aria-hidden="true"></span>
            <span className="visually-hidden">Previous</span>
        </button>
        <button className="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span className="carousel-control-next-icon" aria-hidden="true"></span>
            <span className="visually-hidden">Next</span>
        </button>
      </div>
      </main>
    </div>
  )
}
