import styles from '../../styles/Home.module.css'
import cls from 'classnames'
import Link from 'next/link'
import Head from 'next/head'
const Contact = () =>{
    return(
        <>
        <Head>
            <title> JSB Residences</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/static/logo.ico" />
        </Head>
         <br/><br/><br/><br/><br/>
            <div className='container'>
                <div className={styles.introSingle}>
                    <div className="col-md-12">
                        <div className={cls("bg-warning","bg-gradient","bg-opacity-25",styles.titleSingleBox)}>
                        <h1 className={styles.titleSingle}>Contact - Let&apos;s Connect</h1>
                        </div>
                    </div>
                </div><br/><br/>
            </div>
            <div className='container'>
                <div className="col-sm-12 section-t8">
                    <div className="row">
                    <div className="col-md-7">
                        <form action="" method="post" role="form">
                        <div className="row">
                            <div className="col-md-6 mb-3">
                            <div className="form-group">
                                <input type="text" name="name" className="form-control form-control-lg form-control-a" placeholder="Your Name" required />
                            </div>
                            </div>
                            <div className="col-md-6 mb-3">
                            <div className="form-group">
                                <input name="email" type="email" className="form-control form-control-lg form-control-a" placeholder="Your Email" required />
                            </div>
                            </div>
                            <div className="col-md-12 mb-3">
                            <div className="form-group">
                                <input type="text" name="subject" className="form-control form-control-lg form-control-a" placeholder="Subject" required />
                            </div>
                            </div>
                            <div className="col-md-12">
                            <div className="form-group">
                                <textarea name="message" className="form-control" cols="45" rows="8" placeholder="Message" required></textarea>
                            </div>
                            </div>
                            <div className="col-md-12 my-3">
                            </div>

                            <div className="col-md-12 text-center">
                            <button type="submit" className="btn btn-success btn-lg">Send Message</button>
                            </div>
                        </div>
                        </form><br/>
                    </div>
                    <div className="col-md-5 section-md-t3">
                        <div className="icon-box section-b2">
                        <div className="icon-box-icon">
                            <span className="bi bi-envelope"></span>
                        </div>
                        <div className="icon-box-content table-cell">
                            <div className="icon-box-title">
                            <h4 className="icon-title">Say Hello</h4>
                            </div>
                            <div className="icon-box-content">
                            <p className="mb-1">Email.
                                <span className="color-a">trinityrx4@yahoo.com</span>
                            </p>
                            <p className="mb-1">Phone.
                                <span className="color-a">0927 577 1245</span>
                            </p>
                            </div>
                        </div>
                        </div>
                        <div className="icon-box section-b2">
                        <div className="icon-box-icon">
                            <span className="bi bi-geo-alt"></span>
                        </div>
                        <div className="icon-box-content table-cell">
                            <div className="icon-box-title">
                            <h4 className="icon-title">Find us in</h4>
                            </div>
                            <div className="icon-box-content">
                            <p className="mb-1">
                            Brgy. Disud, Sindangan, Philippines
                            </p>
                            </div>
                        </div>
                        </div>
                        <div className="icon-box">
                        <div className="icon-box-icon">
                            <span className="bi bi-share"></span>
                        </div>
                        <div className="icon-box-content table-cell">
                            <div className="icon-box-title">
                            <h4 className="icon-title">Social networks</h4>
                            </div>
                            <div className="icon-box-content">
                            <div className="socials-footer">
                                <ul className="list-inline">
                                <li className="list-inline-item">
                                    <Link href="https://www.facebook.com/jsbresidencesrealstate" passHref>
                                    <a className="link-one" target="_blank">
                                        <i className="bi bi-facebook" aria-hidden="true"></i>
                                        </a>
                                    </Link>
                                </li>
                                </ul>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default Contact